name: test
on: push
jobs: 
  python_1:
    strategy: 
      matrix: 
        platform: [ubuntu-latest, macos-latest, windows-latest] 
    runs-on: ${{matrix.platform}}
    steps:
      - run: python -c "import platform; print(platform.system())"
